# Generated by Django 4.2.5 on 2023-09-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='uuid',
            field=models.UUIDField(),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('uuid', 'title')},
        ),
    ]
