# Generated by Django 4.2.5 on 2023-09-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_movie_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together=set(),
        ),
    ]
